<template>
	<v-btn-toggle class="ml-auto mr-2">
		<v-btn
			text
			class="mr-4"
			color="chocorate"
		>
			<v-icon
				class="mr-1"
				color="chocorate"
			>
				mdi-github
			</v-icon>
			github
		</v-btn>
		<v-btn
			text
			color="chocorate"
		>
			<v-icon
				class="mr-1"
				color="chocorate"
			>
				mdi-link
			</v-icon>
			SITE URL
		</v-btn>
	</v-btn-toggle>
</template>